server:
  debug: false
  host: "0.0.0.0" # Current machine ip
  port: 5010
  drivers: 'drivers/chromedriver_mac'

database:
  host: "localhost"
  name: "naochallenge2024"
  user: "postgres"
  password: "postgres"

nao:
  ip: "192.168.0.118" #--Ricorda: 192.168.0.118
  port: 9559
  user: "nao"
  password: "nao"  #--Ricorda: nao
  api_openai: "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"

nao2:
  ip: "192.168.0.108"
  port: 9559
  user: "nao"
  password: "KarlTarNAO6."